jobs:
  - job: MINGW
    timeoutInMinutes: 360
    pool:
      vmImage: vs2017-win2016
    strategy:
      maxParallel: 5
      matrix:
        i686:
          RTOOLS_ARCH: x86_64
          MINGW_INSTALLS: mingw32
        x86_64:
          RTOOLS_ARCH: x86_64
          MINGW_INSTALLS: mingw64
    steps:
      - powershell: |
          Import-Module '.\scripts.ps1'
          InstallRtoolsExe
        displayName: Installing msys64 build environment
      - script: |
          SET PATH=c:\rtools40\usr\bin;%PATH%
          rmdir /s /Q "C:\Program Files\Boost"
          copy /y pacman.conf C:\rtools40\etc\pacman.conf
          C:\rtools40\usr\bin\curl -OSsl "http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
          C:\rtools40\usr\bin\pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz && rm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
          C:\rtools40\usr\bin\pacman -Syyuu --noconfirm --ask 20
          C:\rtools40\usr\bin\pacman -Syyuu --noconfirm --ask 20
          C:\rtools40\usr\bin\pacman --noconfirm --needed -S git ca-certificates
          C:\rtools40\usr\bin\bash --login -c "$(cygpath ${SYSTEM_DEFAULTWORKINGDIRECTORY})/ci-build.sh"
        displayName: Building Packages
        env:
          BUILD_URL: dummy
          DEPLOY_PROVIDER: bintray
          BINTRAY_TARGET: rtools
          BINTRAY_REPOSITORY: $(MINGW_INSTALLS)
          PACMAN_REPOSITORY: $(MINGW_INSTALLS)
      - task: PublishPipelineArtifact@1
        displayName: Storing artifacts
        inputs:
          targetPath: artifacts
          artifactName: $(MINGW_INSTALLS)-repo.zip
