jobs:
  - job: MINGW
    timeoutInMinutes: 360
    pool:
      vmImage: vs2017-win2016
    strategy:
      maxParallel: 5
      matrix:
        i686:
          RTOOLS_ARCH: x86_64
          MINGW_INSTALLS: mingw32
        x86_64:
          RTOOLS_ARCH: x86_64
          MINGW_INSTALLS: mingw64
    steps:
      - powershell: |
          Import-Module '.\scripts.ps1'
          InstallMSYS64
          C:\msys64\usr\bin\pacman -Suu --noconfirm --ask 20
        displayName: Installing msys64 build environment
      - script: |
          rmdir /s /Q "C:\Program Files\Boost"
          C:\msys64\usr\bin\pacman --noconfirm --needed -S git
          C:\msys64\usr\bin\bash --login -c "$(cygpath ${SYSTEM_DEFAULTWORKINGDIRECTORY})/ci-build.sh"
        displayName: Building Packages
        env:
          BUILD_URL: dummy
          DEPLOY_PROVIDER: bintray
          BINTRAY_TARGET: rtools
          BINTRAY_REPOSITORY: $(MINGW_INSTALLS)
          PACMAN_REPOSITORY: $(MINGW_INSTALLS)
      - task: PublishPipelineArtifact@1
        displayName: Storing artifacts
        inputs:
          targetPath: artifacts
          artifactName: $(MINGW_INSTALLS)-repo.zip
